services:
  front:
    build:
      context: ../
      dockerfile: ./docker/front/dockerfile
    container_name: front
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./docker/front/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - C:\Users\kanno\.ssh\budget_server.crt:/etc/nginx/ssl/budget_server.crt
      - C:\Users\kanno\.ssh\budget_server.key:/etc/nginx/ssl/budget_server.key
      # html
      # - ./html:/usr/share/nginx/html

#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     restart: always
#     ports: 
#       - "5432:5432"
#     # volumes:
#     #   - ./postgres/init:/docker-entrypoint-initdb.d
#     environment:
#       POSTGRES_USER: "user"
#       POSTGRES_PASSWORD: "postgres"
#       POSTGRES_DB: "budget"
#       POSTGRES_SCHEMS: "public"
      
  # front:
  #   build: ./front # （３）
  #   container_name: front
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0' # （９）
  #   volumes: # （４）
  #     - .:/myapp
  #   ports: # （７）
  #     - "3000:3000"
  #   depends_on: # （８）
  #     - db

#   back:
#     build: ./back # （３）
#     container_name: front
#     command: bundle exec rails s -p 3000 -b '0.0.0.0' # （９）
#     volumes: # （４）
#       - .:/myapp
#     ports: # （７）
#       - "3000:3000"
#     depends_on: # （８）
#       - db
      
# volumes: # （５）
#     db_data: