name: budget
services:
  front:
    build:
      context: ../
      dockerfile: ./docker/front/dockerfile
    container_name: front
    restart: always
    ports:
      - "443:443"
    volumes:
      # - ./docker/front/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - C:\Users\kanno\.ssh\budget_server.crt:/etc/nginx/ssl/budget_server.crt
      - C:\Users\kanno\.ssh\budget_server.key:/etc/nginx/ssl/budget_server.key
      - C:\Users\kanno\.ssh\SAN.txt:/etc/nginx/ssl/SAN.txt
      
  back:
    build:
      context: ../
      dockerfile: ./docker/back/dockerfile
    container_name: back
    restart: always
    ports:
      - "3001:3001"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports: 
      - "5433:5432"
    # volumes:
    #   - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "budget"
      POSTGRES_SCHEMS: "public"