version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres_budget
    ports:
      - 5434:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'budget'
volumes:
  db-store: